version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

  backend:
    build: .
    container_name: flask_app
    ports:
      - 5000:5000
